[versions]
agp = "8.4.0"
kotlin = "1.9.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.0"
constraintlayout = "2.1.4"
hilt = "2.48"
retrofit2 = "2.9.0"
okhttp = "4.9.0"
viewmodel = "2.8.0"
activityktx = "1.6.1"
navigation = "2.7.7"
coroutines = "1.7.3"
fragment = "1.8.1"
glide = "4.16.0"
timber = "5.0.1"
lottie = "5.2.0"
room = "2.6.1"
paging = "3.3.0"

moshi = "1.9.0"
krossbow = "7.1.0"


radarview = "1.0.2"
#fcm
gms = "4.4.2"
firebase-bom = "33.1.2"
firebaseMessagingKtx = "24.0.0"
#location
locations = "21.0.1"
#datastore
datastore = "1.1.1"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
#hilt
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
#retrofit
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp3-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit2" }
#viewmodel
viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "viewmodel" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityktx" }
#navigation
navigation-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
#navigation-safe-args = {group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "navigation"}
#coroutine
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
#fragment
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
#glide
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
#timber
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
#lottie
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }

#room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room"}
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room"}
room-ktx = {group = "androidx.room", name = "room-ktx", version.ref = "room"}

#paging
paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }

#squareup
moshi-kotlin = {group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi"}
converter-scalars = {group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit2"}

#krossbow
krossbow-stomp-core = {group = "org.hildan.krossbow", name = "krossbow-stomp-core", version.ref = "krossbow"}
krossbow-websocket-builtin = {group = "org.hildan.krossbow", name = "krossbow-websocket-builtin", version.ref = "krossbow"}
krossbow-websocket-okhttp = {group = "org.hildan.krossbow", name = "krossbow-websocket-okhttp", version.ref = "krossbow"}
krossbow-stomp-moshi = {group = "org.hildan.krossbow", name = "krossbow-stomp-moshi", version.ref = "krossbow"}

#fcm
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-messaging-ktx = { group = "com.google.firebase", name = "firebase-messaging-ktx", version.ref = "firebaseMessagingKtx" }

#locations
locations = {group = "com.google.android.gms", name= "play-services-location", version.ref = "locations"}

#datastore
datastore = {group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore"}


[bundles]
network = ["retrofit2","okhttp3","okhttp3-logging","gson"]
room = ["room-ktx", "room-runtime"]
squareup = ["moshi-kotlin", "converter-scalars"]
krossbow = ["krossbow-stomp-core", "krossbow-websocket-builtin", "krossbow-websocket-okhttp"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
#fcm
gms-google-services = { id = "com.google.gms.google-services", version.ref = "gms" }
